version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - evanextreme
  ignore:
  - dependency-name: ts-loader
    versions:
    - 9.1.1
  - dependency-name: css-loader
    versions:
    - 5.1.0
  - depenency-name: "*"
    update-types: ["version-update:semver-patch"]
